# Generated by Django 4.2.22 on 2026-09-17 07:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("log_search", "0101_favorite_scope"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportDispatchGate",
            fields=[
                ("namespace", models.CharField(max_length=128, primary_key=True, serialize=False)),
                ("cursor", models.PositiveBigIntegerField(default=0)),
            ],
            options={
                "db_table": "log_export_dispatch_gate",
            },
        ),
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("planning_attempts", models.PositiveIntegerField(default=0)),
                ("planning_generation", models.PositiveBigIntegerField(default=0)),
                ("planning_started_at", models.DateTimeField(blank=True, null=True)),
                ("planning_lease_until", models.DateTimeField(blank=True, null=True)),
                ("next_planning_at", models.DateTimeField(blank=True, null=True)),
                ("space_uid", models.CharField(max_length=256, verbose_name="空间标识")),
                ("created_by", models.CharField(max_length=64, verbose_name="创建者")),
                ("source_app_code", models.CharField(blank=True, default="", max_length=32, verbose_name="来源应用")),
                (
                    "request_id",
                    models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name="幂等请求标识"),
                ),
                (
                    "query_kind",
                    models.CharField(
                        choices=[("single", "单索引"), ("union", "联合查询"), ("scene", "场景检索")],
                        max_length=16,
                        verbose_name="查询类型",
                    ),
                ),
                ("index_set_ids", models.JSONField(blank=True, default=list, verbose_name="原始索引集ID")),
                ("query_snapshot", models.JSONField(verbose_name="规范化查询快照")),
                ("query_hash", models.CharField(max_length=64, verbose_name="查询摘要")),
                ("start_time", models.BigIntegerField(verbose_name="包含的时间下界")),
                ("end_time", models.BigIntegerField(verbose_name="不包含的时间上界")),
                (
                    "time_tick",
                    models.PositiveBigIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)], verbose_name="最小时间步长"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待规划"),
                            ("PLANNING", "规划中"),
                            ("READY", "待调度"),
                            ("RUNNING", "执行中"),
                            ("SUCCESS", "成功"),
                            ("FAILED", "失败"),
                            ("CANCELED", "已取消"),
                        ],
                        default="PENDING",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                ("estimated_total", models.PositiveBigIntegerField(blank=True, null=True, verbose_name="预计行数")),
                ("actual_total", models.PositiveBigIntegerField(default=0, verbose_name="成功叶子实际行数")),
                (
                    "requested_parallelism",
                    models.PositiveSmallIntegerField(
                        default=4,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(8),
                        ],
                        verbose_name="期望并行上限",
                    ),
                ),
                (
                    "current_plan_version",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="当前有效计划版本",
                    ),
                ),
                (
                    "manifest_object_key",
                    models.CharField(blank=True, default="", max_length=1024, verbose_name="有效清单对象键"),
                ),
                (
                    "manifest_checksum",
                    models.CharField(blank=True, default="", max_length=64, verbose_name="清单SHA256"),
                ),
                ("manifest_bytes", models.PositiveBigIntegerField(blank=True, null=True, verbose_name="清单字节数")),
                ("artifacts_cleaned_at", models.DateTimeField(blank=True, null=True, verbose_name="产物清理完成时间")),
                ("finalization_attempts", models.PositiveIntegerField(default=0)),
                ("next_finalization_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="开始时间")),
                ("last_dispatched_at", models.DateTimeField(blank=True, null=True, verbose_name="最近一次投递时间")),
                ("completed_at", models.DateTimeField(blank=True, null=True, verbose_name="完成时间")),
                ("expires_at", models.DateTimeField(blank=True, null=True, verbose_name="成功产物到期时间")),
                ("error_code", models.CharField(blank=True, default="", max_length=64, verbose_name="错误分类")),
                ("error_detail", models.TextField(blank=True, default="", verbose_name="脱敏错误详情")),
            ],
            options={
                "db_table": "log_export_job",
                "unique_together": {("space_uid", "created_by", "request_id")},
            },
        ),
        migrations.CreateModel(
            name="ExportPlan",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "plan_version",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)], verbose_name="计划版本"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNING", "规划中"),
                            ("READY", "已完整持久化"),
                            ("FAILED", "规划失败"),
                        ],
                        default="PLANNING",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                ("planning_input", models.JSONField(blank=True, default=dict, verbose_name="规划输入快照")),
                ("query_hash", models.CharField(max_length=64, verbose_name="查询摘要")),
                ("statistics_at", models.DateTimeField(blank=True, null=True, verbose_name="统计时间")),
                (
                    "target_rows",
                    models.PositiveBigIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)], verbose_name="单片目标行数"
                    ),
                ),
                (
                    "target_bytes",
                    models.PositiveBigIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)], verbose_name="单片目标字节数"
                    ),
                ),
                (
                    "histogram_interval",
                    models.PositiveBigIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)], verbose_name="初始桶宽，单位同Job时间"
                    ),
                ),
                ("part_count", models.PositiveIntegerField(default=0, verbose_name="有效叶子数量")),
                ("error_code", models.CharField(blank=True, default="", max_length=64, verbose_name="错误分类")),
                ("error_detail", models.TextField(blank=True, default="", verbose_name="脱敏错误详情")),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="plans", to="log_search.exportjob"
                    ),
                ),
            ],
            options={
                "db_table": "log_export_plan",
                "unique_together": {("job", "plan_version")},
            },
        ),
        migrations.CreateModel(
            name="ExportPart",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("planning_attempts", models.PositiveIntegerField(default=0)),
                ("planning_generation", models.PositiveBigIntegerField(default=0)),
                ("planning_started_at", models.DateTimeField(blank=True, null=True)),
                ("planning_lease_until", models.DateTimeField(blank=True, null=True)),
                ("next_planning_at", models.DateTimeField(blank=True, null=True)),
                (
                    "part_no",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)], verbose_name="计划内稳定序号"
                    ),
                ),
                ("start_time", models.BigIntegerField(verbose_name="包含的时间下界")),
                ("end_time", models.BigIntegerField(verbose_name="不包含的时间上界")),
                ("is_leaf", models.BooleanField(default=True, verbose_name="有效叶子")),
                ("oversized", models.BooleanField(default=False, verbose_name="不可继续按时间拆分的超量片")),
                ("estimated_rows", models.PositiveBigIntegerField(blank=True, null=True, verbose_name="预计行数")),
                ("estimated_bytes", models.PositiveBigIntegerField(blank=True, null=True, verbose_name="预计字节数")),
                ("actual_rows", models.PositiveBigIntegerField(blank=True, null=True, verbose_name="成功产物实际行数")),
                (
                    "actual_bytes",
                    models.PositiveBigIntegerField(blank=True, null=True, verbose_name="成功产物JSONL字节数"),
                ),
                (
                    "compressed_bytes",
                    models.PositiveBigIntegerField(blank=True, null=True, verbose_name="成功产物压缩字节数"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING", "待投递"),
                            ("DISPATCHED", "已授权投递"),
                            ("RUNNING", "执行中"),
                            ("UPLOADING", "上传中"),
                            ("SUCCESS", "成功"),
                            ("FAILED", "失败"),
                            ("SPLIT", "已拆分"),
                            ("CANCELED", "已取消"),
                        ],
                        default="WAITING",
                        max_length=16,
                        verbose_name="状态",
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DOWNLOAD_LOG", "取数"),
                            ("PACKAGE", "打包"),
                            ("UPLOAD", "上传"),
                            ("FINALIZING", "生成清单"),
                        ],
                        default="",
                        max_length=16,
                        verbose_name="阶段",
                    ),
                ),
                ("attempts", models.PositiveIntegerField(default=0, verbose_name="累计执行次数")),
                ("task_id", models.CharField(blank=True, default="", max_length=255, verbose_name="Celery任务ID")),
                (
                    "lease_id",
                    models.CharField(blank=True, default="", max_length=128, verbose_name="令牌租约所有权标识"),
                ),
                ("lease_until", models.DateTimeField(blank=True, null=True, verbose_name="租约到期时间")),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True, verbose_name="执行心跳")),
                ("next_retry_at", models.DateTimeField(blank=True, null=True, verbose_name="下次允许尝试时间")),
                (
                    "object_key",
                    models.CharField(blank=True, default="", max_length=1024, verbose_name="获胜产物对象键"),
                ),
                ("checksum", models.CharField(blank=True, default="", max_length=64, verbose_name="获胜产物SHA256")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="本次执行开始时间")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="本次执行完成时间")),
                ("error_code", models.CharField(blank=True, default="", max_length=64, verbose_name="错误分类")),
                ("error_detail", models.TextField(blank=True, default="", verbose_name="脱敏错误详情")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="log_search.exportpart",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="parts", to="log_search.exportplan"
                    ),
                ),
            ],
            options={
                "db_table": "log_export_part",
                "unique_together": {("plan", "part_no")},
            },
        ),
        migrations.AddIndex(
            model_name="exportjob",
            index=models.Index(fields=["created_by", "status", "created_at"], name="export_job_user_status"),
        ),
        migrations.AddIndex(
            model_name="exportjob",
            index=models.Index(fields=["space_uid", "created_at", "id"], name="export_job_space_history"),
        ),
        migrations.AddIndex(
            model_name="exportjob",
            index=models.Index(fields=["status", "updated_at"], name="export_job_recovery"),
        ),
        migrations.AddIndex(
            model_name="exportjob",
            index=models.Index(fields=["expires_at"], name="export_job_expiry"),
        ),
        migrations.AddIndex(
            model_name="exportpart",
            index=models.Index(fields=["status", "next_retry_at"], name="export_part_waiting"),
        ),
        migrations.AddIndex(
            model_name="exportpart",
            index=models.Index(fields=["plan", "is_leaf", "status"], name="export_part_plan_leaves"),
        ),
        migrations.AddIndex(
            model_name="exportpart",
            index=models.Index(fields=["lease_until"], name="export_part_lease"),
        ),
    ]
