# Generated by Django 4.2.22 on 2026-09-11 02:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("log_search", "0102_export_job_plan_part"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportpart", name="planning_started_at", field=models.DateTimeField(null=True, blank=True)
        ),
        migrations.AddField(
            model_name="exportpart", name="planning_attempts", field=models.PositiveIntegerField(default=0)
        ),
        migrations.AddField(
            model_name="exportpart", name="planning_generation", field=models.PositiveBigIntegerField(default=0)
        ),
        migrations.AddField(
            model_name="exportpart", name="planning_lease_until", field=models.DateTimeField(null=True, blank=True)
        ),
        migrations.AddField(
            model_name="exportpart", name="next_planning_at", field=models.DateTimeField(null=True, blank=True)
        ),
        migrations.CreateModel(
            name="ExportDispatchGate",
            fields=[
                ("namespace", models.CharField(max_length=128, primary_key=True, serialize=False)),
                ("cursor", models.PositiveBigIntegerField(default=0)),
            ],
            options={
                "db_table": "log_export_dispatch_gate",
            },
        ),
        migrations.AddField(
            model_name="exportjob",
            name="next_planning_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exportjob",
            name="planning_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="exportjob",
            name="planning_generation",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="exportjob",
            name="planning_lease_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exportjob",
            name="planning_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
