# Generated by Django 4.2.22 on 2026-09-11 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("log_search", "0103_export_planning_and_dispatch_gate"),
    ]

    operations = [
        migrations.AddField(
            model_name="exportjob",
            name="finalization_attempts",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="exportjob",
            name="next_finalization_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ExportArtifact",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("object_key", models.CharField(max_length=255, unique=True)),
                ("storage_id", models.CharField(max_length=64)),
                ("checksum", models.CharField(max_length=64)),
                ("content_checksum", models.CharField(blank=True, default="", max_length=64)),
                ("size", models.PositiveBigIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("UPLOADING", "Uploading"), ("READY", "Ready")],
                        default="UPLOADING",
                        max_length=16,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="artifacts", to="log_search.exportjob"
                    ),
                ),
            ],
            options={
                "db_table": "log_export_artifact",
                "indexes": [models.Index(fields=["job", "status"], name="export_artifact_cleanup")],
            },
        ),
        migrations.RemoveIndex(
            model_name="exportplan",
            name="export_plan_recovery",
        ),
        migrations.RemoveField(
            model_name="exportplan",
            name="planning_heartbeat",
        ),
        migrations.RemoveField(
            model_name="exportjob",
            name="stage",
        ),
    ]
